# Smoke test to verify that the JVM starts correctly and that the required
# Java classes (Fges, TimeLagGraph) are available in the Tetrad JAR.
# Usage: python test_tsfges.py --data-csv data.csv [--jar path/tetrad.jar] [--penalty-discount 2.0]
#        python test_tsfges.py --data-npy data.npy  (alternative if you have a .npy array)

from __future__ import annotations

# pyright: reportMissingImports=false

import argparse
import os
import tempfile
from pathlib import Path

import jpype
import jpype.imports
import numpy as np


def _resolve_jvm_path() -> str:
    # 1. Explicitly defined JAVA_HOME
    java_home = os.getenv("JAVA_HOME")
    if java_home:
        candidate = Path(java_home) / "bin" / "server" / "jvm.dll"
        if candidate.exists():
            return str(candidate)
        candidate = Path(java_home) / "bin" / "client" / "jvm.dll"
        if candidate.exists():
            return str(candidate)

    # 2. Search in known Eclipse Adoptium / Oracle paths on Windows
    search_roots = [
        Path(os.getenv("LOCALAPPDATA", "")) / "Programs" / "Eclipse Adoptium",
        Path("C:/Program Files/Eclipse Adoptium"),
        Path("C:/Program Files/Java"),
        Path("C:/Program Files/Microsoft"),
    ]
    for root in search_roots:
        for jvm_dll in sorted(root.rglob("jvm.dll"), reverse=True):
            return str(jvm_dll)

    # 3. Let JPype handle discovery as a last resort
    return jpype.getDefaultJVMPath()


def _resolve_tetrad_jar(cli_jar: str | None) -> Path:
    if cli_jar:
        return Path(cli_jar).expanduser().resolve()

    env_jar = os.getenv("TETRAD_JAR")
    if env_jar:
        return Path(env_jar).expanduser().resolve()

    # Automatic search: libs/ at the project root
    # (three levels up from src/tsfges/test_tsfges/)
    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    for candidate in sorted((repo_root / "libs").glob("tetrad*.jar")):
        return candidate

    raise FileNotFoundError(
        "Tetrad JAR not found.\n"
        "Options:\n"
        "  1. Pass --jar <path/tetrad.jar>\n"
        "  2. Set environment variable TETRAD_JAR=<path/tetrad.jar>\n"
        f"  3. Place the JAR in {repo_root / 'libs'}\\"
    )


def _prepare_csv_for_tetrad(
    csv_path: str | None, npy_path: str | None
) -> tuple[Path, bool]:
    if csv_path:
        path = Path(csv_path).expanduser().resolve()
        if not path.exists():
            raise FileNotFoundError(f"CSV file not found: {path}")
        return path, False

    if npy_path:
        npy = Path(npy_path).expanduser().resolve()
        if not npy.exists():
            raise FileNotFoundError(f"NPY file not found: {npy}")

        data = np.load(npy)
        if data.ndim != 2:
            raise ValueError(
                "The NPY file must be 2D (n_samples, n_vars)."
            )

        tmp = tempfile.NamedTemporaryFile(
            prefix="tetrad_dataset_",
            suffix=".csv",
            delete=False,
            mode="w",
            newline="",
            encoding="utf-8",
        )
        tmp_path = Path(tmp.name)
        tmp.close()

        header = ",".join(f"X{i}" for i in range(data.shape[1]))
        np.savetxt(tmp_path, data, delimiter=",", header=header, comments="")
        return tmp_path, True

    raise ValueError("You must provide either --data-csv or --data-npy.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Smoke test: start the JVM and import "
            "Fges + TimeLagGraph for TS-FGES"
        )
    )
    parser.add_argument(
        "--jar",
        help="Path to the tetrad-current.jar file",
    )
    parser.add_argument(
        "--data-csv",
        help="Path to a CSV dataset (with header) generated by other scripts.",
    )
    parser.add_argument(
        "--data-npy",
        help=(
            "Path to a 2D NPY dataset (n_samples, n_vars) "
            "generated by other scripts."
        ),
    )
    parser.add_argument(
        "--penalty-discount",
        type=float,
        default=2.0,
        help="Penalty discount for SemBicScore (default: 2.0).",
    )
    args = parser.parse_args()

    jar_path = _resolve_tetrad_jar(args.jar)
    if not jar_path.exists():
        raise FileNotFoundError(f"JAR file not found: {jar_path}")

    if not jpype.isJVMStarted():
        jvm_path = _resolve_jvm_path()
        jpype.startJVM(jvm_path, classpath=[str(jar_path)])

    # Dynamic import of Java classes after the JVM is started.
    from java.io import File
    from edu.cmu.tetrad.graph import TimeLagGraph
    from edu.cmu.tetrad.search import Fges
    from edu.cmu.tetrad.search.score import SemBicScore
    from edu.cmu.tetrad.data import SimpleDataLoader
    from edu.pitt.dbmi.data.reader import Delimiter

    print(f"JVM started with: {jar_path}")
    print(f"Import OK: {Fges}")
    print(f"Import OK: {TimeLagGraph}")


    csv_file, is_temp_csv = _prepare_csv_for_tetrad(
        args.data_csv, args.data_npy
    )

    try:
        dataset = SimpleDataLoader.loadContinuousData(
            File(str(csv_file)),
            "//",
            '"',
            "*",
            True,
            Delimiter.COMMA,
            False,
        )
        score = SemBicScore(dataset, True)
        score.setPenaltyDiscount(args.penalty_discount)
        fges = Fges(score)
        graph = fges.search()

        print(f"Dataset loaded: {csv_file}")
        print(f"FGES nodes: {graph.getNumNodes()}")
        print(f"FGES edges: {graph.getNumEdges()}")
    finally:
        if is_temp_csv and csv_file.exists():
            csv_file.unlink()


if __name__ == "__main__":
    main()
